/* ================================================================
   data.js — All product data lives here
   Update prices, stock, links, descriptions, and specs in this file
================================================================ */

// type: "Air Handler & Condenser" = complete system (indoor + outdoor unit)
// Only products with this type will be shown on the site.
const PRODUCTS = [
  {
    id: "9k",
    type: "Air Handler & Condenser",
    name: "9,000 BTU Mini Split",
    btu: 9000,
    generation: "Advantage 5th Gen",
    sku: "A-09-HP-230D",
    voltage: "230V",
    plugIn: false,
    featured: false,
    coverage: "Up to 450 sq ft",
    seer: 20,
    popular: false,
    bestFor: "Bedrooms & home offices",
    description: "Ideal for bedrooms, home offices, and small living spaces. Whisper-quiet operation at just 26 dB makes it barely noticeable while you sleep or work.",
    features: ["20 SEER2 Rating", "WiFi Enabled", "Sleep Mode", "Auto Restart"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Electrical disconnect box",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":     "9,000 BTU",
      "Coverage Area":    "Up to 450 sq ft",
      "SEER2 Rating":     "20 SEER2",
      "Noise Level":      "26 dB (indoor)",
      "Voltage":          "208–230V / 60Hz",
      "Heating Mode":     "Yes (heat pump)",
      "WiFi Control":     "Yes",
      "Compressor Type":  "DC Inverter",
      "Refrigerant":      "R-410A",
      "Warranty":         "7-year compressor, 5-year parts"
    },
    stock: 4,
    mrcool: { price: 729,  image: "images/mrcool/9k.jpg",  url: "#" },
    depot:  { price: 656,  image: "images/depot/9k.jpg",   url: "#" }
  },
  {
    id: "12k",
    type: "Air Handler & Condenser",
    name: "12,000 BTU Mini Split",
    btu: 12000,
    generation: "Advantage 5th Gen",
    sku: "A-12-HP-230D",
    voltage: "230V",
    plugIn: false,
    featured: true,
    coverage: "Up to 600 sq ft",
    seer: 20,
    popular: true,
    bestFor: "Master bedrooms & living rooms",
    description: "Our best-selling unit — the sweet spot of price and performance for most single rooms. Cools a master bedroom or medium living room fast with precise, quiet comfort.",
    features: ["20 SEER2 Rating", "WiFi Enabled", "Dehumidification Mode", "Auto Restart"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Electrical disconnect box",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":     "12,000 BTU",
      "Coverage Area":    "Up to 600 sq ft",
      "SEER2 Rating":     "20 SEER2",
      "Noise Level":      "28 dB (indoor)",
      "Voltage":          "208–230V / 60Hz",
      "Heating Mode":     "Yes (heat pump)",
      "WiFi Control":     "Yes",
      "Compressor Type":  "DC Inverter",
      "Refrigerant":      "R-410A",
      "Warranty":         "7-year compressor, 5-year parts"
    },
    stock: 9,
    mrcool: { price: 899,  image: "images/mrcool/12k.jpg", url: "#" },
    depot:  { price: 809,  image: "images/depot/12k.jpg",  url: "#" }
  },
  {
    id: "18k",
    type: "Air Handler & Condenser",
    name: "18,000 BTU Mini Split",
    btu: 18000,
    generation: "Advantage 5th Gen",
    sku: "A-18-HP-230D",
    voltage: "230V",
    plugIn: false,
    featured: true,
    coverage: "Up to 900 sq ft",
    seer: 20,
    popular: false,
    bestFor: "Large rooms & open-plan spaces",
    description: "Perfect for large bedrooms, open-plan living areas, and combined kitchen/dining rooms. Handles extreme outdoor temperatures effortlessly without breaking a sweat.",
    features: ["20 SEER2 Rating", "WiFi Enabled", "Turbo Mode", "Self-Cleaning"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Electrical disconnect box",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":     "18,000 BTU",
      "Coverage Area":    "Up to 900 sq ft",
      "SEER2 Rating":     "20 SEER2",
      "Noise Level":      "32 dB (indoor)",
      "Voltage":          "208–230V / 60Hz",
      "Heating Mode":     "Yes (heat pump)",
      "WiFi Control":     "Yes",
      "Compressor Type":  "DC Inverter",
      "Refrigerant":      "R-410A",
      "Warranty":         "7-year compressor, 5-year parts"
    },
    stock: 3,
    mrcool: { price: 1099, image: "images/mrcool/18k.jpg", url: "#" },
    depot:  { price: 989,  image: "images/depot/18k.jpg",  url: "#" }
  },
  {
    id: "24k",
    type: "Air Handler & Condenser",
    name: "24,000 BTU Mini Split",
    btu: 24000,
    generation: "Advantage 5th Gen",
    sku: "A-24-HP-230D",
    voltage: "230V",
    plugIn: false,
    featured: false,
    coverage: "Up to 1,200 sq ft",
    seer: 17,
    popular: false,
    bestFor: "Great rooms & large open areas",
    description: "Built for large open areas, great rooms, and combined living spaces up to 1,200 sq ft. High-efficiency performance holds up year-round in climates from Alaska to Texas.",
    features: ["17 SEER2 Rating", "WiFi Enabled", "Turbo Mode", "Self-Cleaning"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Electrical disconnect box",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":     "24,000 BTU",
      "Coverage Area":    "Up to 1,200 sq ft",
      "SEER2 Rating":     "17 SEER2",
      "Noise Level":      "34 dB (indoor)",
      "Voltage":          "208–230V / 60Hz",
      "Heating Mode":     "Yes (heat pump)",
      "WiFi Control":     "Yes",
      "Compressor Type":  "DC Inverter",
      "Refrigerant":      "R-410A",
      "Warranty":         "7-year compressor, 5-year parts"
    },
    stock: 11,
    mrcool: { price: 1349, image: "images/mrcool/24k.jpg", url: "#" },
    depot:  { price: 1214, image: "images/depot/24k.jpg",  url: "#" }
  },
  {
    id: "36k",
    type: "Air Handler & Condenser",
    name: "36,000 BTU Mini Split",
    btu: 36000,
    generation: "Advantage 5th Gen",
    sku: "A-36-HP-230D",
    voltage: "230V",
    plugIn: false,
    featured: false,
    coverage: "Up to 1,800 sq ft",
    seer: 18,
    popular: false,
    bestFor: "Large homes, workshops & garages",
    description: "Maximum power for large homes, detached garages, workshops, and commercial applications. Professional-grade efficiency that scales to meet demanding environments.",
    features: ["18 SEER2 Rating", "WiFi Enabled", "Turbo Mode", "Auto-Diagnosis"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Electrical disconnect box",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":     "36,000 BTU",
      "Coverage Area":    "Up to 1,800 sq ft",
      "SEER2 Rating":     "18 SEER2",
      "Noise Level":      "38 dB (indoor)",
      "Voltage":          "208–230V / 60Hz",
      "Heating Mode":     "Yes (heat pump)",
      "WiFi Control":     "Yes",
      "Compressor Type":  "DC Inverter",
      "Refrigerant":      "R-410A",
      "Warranty":         "7-year compressor, 5-year parts"
    },
    stock: 2,
    mrcool: { price: 1699, image: "images/mrcool/36k.jpg", url: "#" },
    depot:  { price: 1529, image: "images/depot/36k.jpg",  url: "#" }
  },

  // ── 115V PLUG-IN VARIANTS (no electrician required) ─────────────
  {
    id: "9k-115v",
    type: "Air Handler & Condenser",
    name: "9,000 BTU Mini Split — 115V Plug-In",
    btu: 9000,
    generation: "Advantage 5th Gen",
    sku: "A-09-HP-115D",
    voltage: "115V",
    plugIn: true,
    featured: false,
    coverage: "Up to 450 sq ft",
    seer: 20,
    popular: false,
    bestFor: "Bedrooms & offices — no electrician needed",
    description: "Plugs into any standard 115V/20A outlet — zero electrician required. All the performance of a full-size 9k unit with the easiest installation on the market. Perfect for apartments, condos, and anywhere a new 240V circuit isn't practical.",
    features: ["20 SEER2 Rating", "115V / Plug-In", "WiFi Enabled", "Sleep Mode", "No Electrician"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Standard 115V power cord",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":       "9,000 BTU",
      "Coverage Area":      "Up to 450 sq ft",
      "SEER2 Rating":       "20 SEER2",
      "Noise Level":        "26 dB (indoor)",
      "Voltage":            "115V / 60Hz",
      "Required Circuit":   "Standard 20A household outlet",
      "Electrician Needed": "No — plug-in ready",
      "Heating Mode":       "Yes (heat pump)",
      "WiFi Control":       "Yes",
      "Compressor Type":    "DC Inverter",
      "Refrigerant":        "R-410A",
      "Warranty":           "7-year compressor, 5-year parts"
    },
    stock: 6,
    mrcool: { price: 799,  image: "images/mrcool/9k.jpg",  url: "#" },
    depot:  { price: 719,  image: "images/depot/9k.jpg",   url: "#" }
  },
  {
    id: "12k-115v",
    type: "Air Handler & Condenser",
    name: "12,000 BTU Mini Split — 115V Plug-In",
    btu: 12000,
    generation: "Advantage 5th Gen",
    sku: "A-12-HP-115D",
    voltage: "115V",
    plugIn: true,
    featured: true,
    coverage: "Up to 600 sq ft",
    seer: 20,
    popular: false,
    bestFor: "Living rooms & large bedrooms — no electrician needed",
    description: "The most convenient full-size mini split on the market. Plug into a standard 115V/20A outlet — no electrician, no dedicated circuit, no electrical permit. Install it yourself in a weekend.",
    features: ["20 SEER2 Rating", "115V / Plug-In", "WiFi Enabled", "Dehumidification", "No Electrician"],
    includedItems: [
      "Indoor wall-mounted unit",
      "Outdoor condenser unit",
      "25 ft pre-charged lineset",
      "Standard 115V power cord",
      "Mounting bracket & hardware",
      "Remote control",
      "Installation manual"
    ],
    specs: {
      "BTU Capacity":       "12,000 BTU",
      "Coverage Area":      "Up to 600 sq ft",
      "SEER2 Rating":       "20 SEER2",
      "Noise Level":        "28 dB (indoor)",
      "Voltage":            "115V / 60Hz",
      "Required Circuit":   "Standard 20A household outlet",
      "Electrician Needed": "No — plug-in ready",
      "Heating Mode":       "Yes (heat pump)",
      "WiFi Control":       "Yes",
      "Compressor Type":    "DC Inverter",
      "Refrigerant":        "R-410A",
      "Warranty":           "7-year compressor, 5-year parts"
    },
    stock: 7,
    mrcool: { price: 949,  image: "images/mrcool/12k.jpg", url: "#" },
    depot:  { price: 854,  image: "images/depot/12k.jpg",  url: "#" }
  }
].filter(p => p.type === "Air Handler & Condenser");
